steps:
- download: current
  displayName: Download deployables
  artifact: SignedPackages

- task: NuGetCommand@2
  displayName: Push packages to Azure DevOps private feed
  inputs:
    command: push
    packagesToPush: $(Pipeline.Workspace)/SignedPackages/*.nupkg
    nuGetFeedType: internal
    publishVstsFeed: $(ci_feed)
    allowPackageConflicts: true
  condition: and(succeeded(), ne(variables['ci_feed'], ''), ne(variables['Build.Reason'], 'PullRequest'))

- task: NuGetCommand@2
  displayName: Push packages to Azure DevOps public feed
  inputs:
    command: 'push'
    packagesToPush: $(Pipeline.Workspace)/SignedPackages/*.nupkg
    nuGetFeedType: 'external'
    publishFeedCredentials: 'MobileBlazorBindings-Packages-nightly'
  condition: and(succeeded(), ne(variables['ci_feed'], ''), ne(variables['Build.Reason'], 'PullRequest'))
